/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */





#include "Platform_Types.h"
#define GPIO_A_base_add     0x40010800
#define GPIO_B_base_add     0x40010C00
#define RCC_Base_address    0x40021000

#define RCC_APB2ENR *((vuint_32*)(RCC_Base_address + 0x18))

#define GPIOA_CRL 	*((vuint_32 *)(GPIO_A_base_add + 0x00))
#define GPIOA_CRH 	*((vuint_32 *)(GPIO_A_base_add + 0x04))
#define GPIOA_IDR 	*((vuint_32 *)(GPIO_A_base_add + 0x08))
#define GPIOA_ODR 	*((vuint_32 *)(GPIO_A_base_add + 0x0C))

#define GPIOB_CRL 	*(vuint_32 *)(GPIO_B_base_add + 0x00)
#define GPIOB_CRH 	*(vuint_32 *)(GPIO_B_base_add + 0x04)
#define GPIOB_IDR 	*(vuint_32 *)(GPIO_B_base_add + 0x08)
#define GPIOB_ODR 	*(vuint_32 *)(GPIO_B_base_add + 0x0C)


void my_wait(vuint_32 x)
{
	vuint_32 y,z;
for(y=0;y<x;y++)
	for(z=0;z<255;z++);

}
void RCC_init()
{

		    // Bit 3 IOPBEN: I/O port B clock enable
			// Set and cleared by software.
			// 0: I/O port B clock disabled
			// 1:I/O port B clock enabled


	RCC_APB2ENR |= 1<<3;


		//	 Bit 2 IOPAEN: I/O port A clock enable
			// Set and cleared by software.
			// 0: I/O port A clock disabled
			// 1:I/O port A clock enabled


	RCC_APB2ENR |= 1<<2;
}


void GPIO_OUTPUT_init()
{
	GPIOB_CRL=0;
	GPIOB_CRH=0;

	// CNF 00: General purpose output push-pull

	//B1
	// Mode Output 10Mhz 01
	GPIOB_CRL |= (0b01<<4);
	//B13
	// Mode Output 10Mhz
	GPIOB_CRH |=(0b01<<20);
}

void GPIO_Input_init()
{




	//A1
	GPIOA_CRL |= (0b01<<6);
	//A13
	GPIOA_CRH |=(0b01<<22);
}
int main(void)
{
	 RCC_init();
	 GPIO_OUTPUT_init();
	 GPIO_Input_init();

	while(1)
	{
		if ((GPIOA_IDR &(1<<1))>>1 == 0)
		{
			GPIOB_ODR ^=(1<<1);
			while((GPIOA_IDR &(1<<1))>>1 == 0);
		}

		if((GPIOA_IDR &(1<<13))>>13 == 1)
		{
			GPIOB_ODR ^=(1<<13);
		}

		my_wait(300);
	}
	return 0;
}




