/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */





#include "Platform_Types.h"
#include "stm32_F103C6_GPIO_Driver.h"
#include "stm32f103x6.h"


void my_wait(vuint_32 x)
{
	vuint_32 y,z;
for(y=0;y<x;y++)
	for(z=0;z<255;z++);

}
void RCC_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}




void GPIO_init()
{

	GPIO_PinConfig_t PIN_CONFIG;
	PIN_CONFIG.GPIO_PinNumber=GPIO_PINS_1;
	PIN_CONFIG.GPIO_Mode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PIN_CONFIG);

	PIN_CONFIG.GPIO_PinNumber=GPIO_PINS_13;
	PIN_CONFIG.GPIO_Mode=GPIO_MODE_INPUT_FLO;
    MCAL_GPIO_Init(GPIOA, &PIN_CONFIG);

    PIN_CONFIG.GPIO_PinNumber=GPIO_PINS_1;
    PIN_CONFIG.GPIO_Mode=GPIO_MODE_OUTPUT_PP;
    PIN_CONFIG.GPIO_OUTPUT_Speed=GPIO_SPEED_10MHz;
    MCAL_GPIO_Init(GPIOB, &PIN_CONFIG);

    PIN_CONFIG.GPIO_PinNumber=GPIO_PINS_13;
    PIN_CONFIG.GPIO_Mode=GPIO_MODE_OUTPUT_PP;
    PIN_CONFIG.GPIO_OUTPUT_Speed=GPIO_SPEED_10MHz;
    MCAL_GPIO_Init(GPIOB, &PIN_CONFIG);

}
int main(void)
{
	 RCC_init();
	 GPIO_init();

	while(1)
	{

		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_1)== GPIO_PINS_State_RESET)
				{
					MCAL_GPIO_TogglePin(GPIOB, GPIO_PINS_1);
					while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_1)== GPIO_PINS_State_RESET);
				}

				if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_13)== GPIO_PINS_State_SET)
				{
					MCAL_GPIO_TogglePin(GPIOB, GPIO_PINS_13);
				}

				my_wait(300);

	}


	return 0;
}




